/// Flutter icons HabityIcons
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  HabityIcons
///      fonts:
///       - asset: fonts/HabityIcons.ttf
///
///
///
import 'package:flutter/widgets.dart';

class HabityIcons {
  HabityIcons._();

  static const _kFontFam = 'HabityIcons';
  static const String? _kFontPkg = null;

  static const IconData breakfastDining =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cleanHands =
      IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData faceRetouchingNatural =
      IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData emojiEvents =
      IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData settings =
      IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData taskAlt =
      IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData kingBed =
      IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData waterDrop =
      IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icRoundAddTask =
      IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
