// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATpry6vcDhQKVXqPbAOVq_f-nEP2ldKhs',
    appId: '1:443723990346:web:d01eaa2b76ad7e24396db3',
    messagingSenderId: '443723990346',
    projectId: 'habitoskids-183cf',
    authDomain: 'habitoskids-183cf.firebaseapp.com',
    storageBucket: 'habitoskids-183cf.appspot.com',
    measurementId: 'G-WYHJL3SYNV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTtqlHDNxGWLP_inbzQOb_BDVOubQDgP4',
    appId: '1:443723990346:android:b3de0867a206af99396db3',
    messagingSenderId: '443723990346',
    projectId: 'habitoskids-183cf',
    storageBucket: 'habitoskids-183cf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTLINPvE6xdjqIX8My3PtNQjJup477xHY',
    appId: '1:443723990346:ios:17fa4f0450f79cb9396db3',
    messagingSenderId: '443723990346',
    projectId: 'habitoskids-183cf',
    storageBucket: 'habitoskids-183cf.appspot.com',
    iosClientId:
        '443723990346-3imlmdkp93r79vpjgg0h1ckk350sfe8q.apps.googleusercontent.com',
    iosBundleId: 'kids.habits.com',
  );
}
