import 'package:habitos/theme/habity_icons_icons.dart';

List icons = [
  {'name': 'breakfastDining', 'icon': HabityIcons.breakfastDining},
  {'name': 'cleanHands', 'icon': HabityIcons.cleanHands},
  {'name': 'faceRetouchingNatural', 'icon': HabityIcons.faceRetouchingNatural},
  {'name': 'emojiEvents', 'icon': HabityIcons.emojiEvents},
  {'name': 'settings', 'icon': HabityIcons.settings},
  {'name': 'taskAlt', 'icon': HabityIcons.taskAlt},
  {'name': 'kingBed', 'icon': HabityIcons.kingBed},
  {'name': 'waterDrop', 'icon': HabityIcons.waterDrop},
  {'name': 'icRroundAddTask', 'icon': HabityIcons.icRroundAddTask},
  {'name': 'amusementParkCastle', 'icon': HabityIcons.amusementParkCastle},
  {
    'name': 'amusementParkFerrisWheel_1',
    'icon': HabityIcons.amusementParkFerrisWheel_1
  },
  {
    'name': 'astronomyPlanetRingStar',
    'icon': HabityIcons.astronomyPlanetRingStar
  },
  {'name': 'awardTrophyStar', 'icon': HabityIcons.awardTrophyStar},
  {'name': 'bathroomShower', 'icon': HabityIcons.bathroomShower},
  {'name': 'beachPalmSunbed', 'icon': HabityIcons.beachPalmSunbed},
  {'name': 'bearBody', 'icon': HabityIcons.bearBody},
  {'name': 'bird', 'icon': HabityIcons.bird},
  {'name': 'brainHead_1', 'icon': HabityIcons.brainHead_1},
  {'name': 'breadFree', 'icon': HabityIcons.breadFree},
  {'name': 'breakfastCroissant_2', 'icon': HabityIcons.breakfastCroissant_2},
  {'name': 'camera_1', 'icon': HabityIcons.camera_1},
  {'name': 'campingTent_1', 'icon': HabityIcons.campingTent_1},
  {'name': 'catFishToy', 'icon': HabityIcons.catFishToy},
  {'name': 'catSitting', 'icon': HabityIcons.catSitting},
  {'name': 'chessFigures', 'icon': HabityIcons.chessFigures},
  {'name': 'chick_1', 'icon': HabityIcons.chick_1},
  {'name': 'circusTent_1', 'icon': HabityIcons.circusTent_1},
  {'name': 'colorPaintingPalette', 'icon': HabityIcons.colorPaintingPalette},
  {'name': 'concertDj', 'icon': HabityIcons.concertDj},
  {'name': 'concertRock', 'icon': HabityIcons.concertRock},
  {'name': 'concertSpeakers', 'icon': HabityIcons.concertSpeakers},
  {
    'name': 'craftsOrigamiAlternate',
    'icon': HabityIcons.craftsOrigamiAlternate
  },
  {'name': 'datingChatMan', 'icon': HabityIcons.datingChatMan},
  {'name': 'deer_1', 'icon': HabityIcons.deer_1},
  {'name': 'dentistryToothBrush', 'icon': HabityIcons.dentistryToothBrush},
  {'name': 'designDraw', 'icon': HabityIcons.designDraw},
  {'name': 'divingMask', 'icon': HabityIcons.divingMask},
  {'name': 'dogBone', 'icon': HabityIcons.dogBone},
  {'name': 'dogLeash', 'icon': HabityIcons.dogLeash},
  {'name': 'ecologyPlantHand_1', 'icon': HabityIcons.ecologyPlantHand_1},
  {'name': 'drugsPill', 'icon': HabityIcons.drugsPill},
  {'name': 'dog', 'icon': HabityIcons.dog},
  {'name': 'elephantWater', 'icon': HabityIcons.elephantWater},
  {'name': 'familyChild', 'icon': HabityIcons.familyChild},
  {'name': 'fastFoodBurger', 'icon': HabityIcons.fastFoodBurger},
  {'name': 'fastFoodPizza', 'icon': HabityIcons.fastFoodPizza},
  {'name': 'fishBowl', 'icon': HabityIcons.fishBowl},
  {
    'name': 'familyOutdoorsPlayhouseSwing',
    'icon': HabityIcons.familyOutdoorsPlayhouseSwing
  },
  {'name': 'flower_1', 'icon': HabityIcons.flower_1},
  {'name': 'foxTail', 'icon': HabityIcons.foxTail},
  {'name': 'fruitWatermelon_1', 'icon': HabityIcons.fruitWatermelon_1},
  {'name': 'gardeningTools', 'icon': HabityIcons.gardeningTools},
  {'name': 'gardeningWateringPipe', 'icon': HabityIcons.gardeningWateringPipe},
  {'name': 'gardeningLawnMower_1', 'icon': HabityIcons.gardeningLawnMower_1},
  {'name': 'fruitWatermelon', 'icon': HabityIcons.fruitWatermelon},
  {'name': 'giftBox', 'icon': HabityIcons.giftBox},
  {'name': 'hairDressComb', 'icon': HabityIcons.hairDressComb},
  {'name': 'hotelBed', 'icon': HabityIcons.hotelBed},
  {'name': 'instrumentPianoKeys', 'icon': HabityIcons.instrumentPianoKeys},
  {'name': 'like_1', 'icon': HabityIcons.like_1},
  {'name': 'livestockCowBody', 'icon': HabityIcons.livestockCowBody},
  {'name': 'loveItCircle', 'icon': HabityIcons.loveItCircle},
  {'name': 'lovePlant', 'icon': HabityIcons.lovePlant},
  {
    'name': 'messagesBubbleSquareSmile',
    'icon': HabityIcons.messagesBubbleSquareSmile
  },
  {'name': 'modernMusicBassGuitar', 'icon': HabityIcons.modernMusicBassGuitar},
  {'name': 'microphoneKaraoke_1', 'icon': HabityIcons.microphoneKaraoke_1},
  {'name': 'modernMusicCymbal', 'icon': HabityIcons.modernMusicCymbal},
  {'name': 'medicalFolder', 'icon': HabityIcons.medicalFolder},
  {'name': 'moodHappy', 'icon': HabityIcons.moodHappy},
  {'name': 'movieCinemaWatch_1', 'icon': HabityIcons.movieCinemaWatch_1},
  {'name': 'musicGenreBaby', 'icon': HabityIcons.musicGenreBaby},
  {'name': 'musicGenreMoon', 'icon': HabityIcons.musicGenreMoon},
  {'name': 'musicNote_1', 'icon': HabityIcons.musicNote_1},
  {
    'name': 'nauticSportsSailingPerson',
    'icon': HabityIcons.nauticSportsSailingPerson
  },
  {'name': 'outdoorsBenchSit', 'icon': HabityIcons.outdoorsBenchSit},
  {'name': 'outdoorsCampFire', 'icon': HabityIcons.outdoorsCampFire},
  {'name': 'outdoorsHorse', 'icon': HabityIcons.outdoorsHorse},
  {'name': 'outdoorsKiteFlying', 'icon': HabityIcons.outdoorsKiteFlying},
  {'name': 'partyBalloon', 'icon': HabityIcons.partyBalloon},
  {'name': 'plane_1', 'icon': HabityIcons.plane_1},
  {'name': 'plantSmile', 'icon': HabityIcons.plantSmile},
  {'name': 'rabbitSide', 'icon': HabityIcons.rabbitSide},
  {'name': 'rankingWinnerBadge', 'icon': HabityIcons.rankingWinnerBadge},
  {'name': 'ratingStarCircle', 'icon': HabityIcons.ratingStarCircle},
  {'name': 'readGlasses_1', 'icon': HabityIcons.readGlasses_1},
  {'name': 'recyclingHandTrash', 'icon': HabityIcons.recyclingHandTrash},
  {'name': 'recyclingTrashBin_2', 'icon': HabityIcons.recyclingTrashBin_2},
  {'name': 'religionBible', 'icon': HabityIcons.religionBible},
  {'name': 'sailingBoatWater_1', 'icon': HabityIcons.sailingBoatWater_1},
  {'name': 'religionCross', 'icon': HabityIcons.religionCross},
  {'name': 'restaurantEatingSet', 'icon': HabityIcons.restaurantEatingSet},
  {'name': 'savingPiggyBank', 'icon': HabityIcons.savingPiggyBank},
  {'name': 'schoolBag', 'icon': HabityIcons.schoolBag},
  {'name': 'schoolBookApple', 'icon': HabityIcons.schoolBookApple},
  {'name': 'scienceFictionShip', 'icon': HabityIcons.scienceFictionShip},
  {'name': 'shirtPlain', 'icon': HabityIcons.shirtPlain},
  {'name': 'showHatMagician_1', 'icon': HabityIcons.showHatMagician_1},
  {'name': 'smileyAngry', 'icon': HabityIcons.smileyAngry},
  {'name': 'smileyBlessed', 'icon': HabityIcons.smileyBlessed},
  {'name': 'smileyLolAlternate_1', 'icon': HabityIcons.smileyLolAlternate_1},
  {'name': 'spaceBase', 'icon': HabityIcons.spaceBase},
  {'name': 'spaceRocket_2', 'icon': HabityIcons.spaceRocket_2},
  {'name': 'studyLightIdea', 'icon': HabityIcons.studyLightIdea},
  {'name': 'tigerBengal', 'icon': HabityIcons.tigerBengal},
  {'name': 'toolsWenchHold', 'icon': HabityIcons.toolsWenchHold},
  {'name': 'treeTwo', 'icon': HabityIcons.treeTwo},
  {'name': 'tvDisable', 'icon': HabityIcons.tvDisable},
  {'name': 'tvFlatScreenDisable', 'icon': HabityIcons.tvFlatScreenDisable},
  {'name': 'trendsHotFlame', 'icon': HabityIcons.trendsHotFlame},
  {'name': 'vegetablesBroccoli_1', 'icon': HabityIcons.vegetablesBroccoli_1},
  {'name': 'vegetablesCarrot', 'icon': HabityIcons.vegetablesCarrot},
  {'name': 'videoGameMagicWand', 'icon': HabityIcons.videoGameMagicWand},
  {'name': 'videoGameMarioFlower', 'icon': HabityIcons.videoGameMarioFlower},
  {'name': 'videoGamePotion', 'icon': HabityIcons.videoGamePotion},
  {'name': 'videoGameShwings', 'icon': HabityIcons.videoGameShwings},
  {
    'name': 'videoGameXboxController',
    'icon': HabityIcons.videoGameXboxController
  },
  {
    'name': 'wildlifeProtectionHold',
    'icon': HabityIcons.wildlifeProtectionHold
  },
];
